name: Github Pages Deploy

on:
  push:
    branches: [ "master", "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Remove package-lock.json
        run: rm package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment